### ISSUE TITLE
How to access width/height?

### ISSUE THREAD

**Issue by huglester** [WeDreamPro/PyroCMS-Video-URL-FieldType#4]
Hello,

I have set up width to 100 and height to 100...
But when I dump at pre_output_plugin, 
it has smth like:
iframe src="http://www.youtube.com/embed/XXXXXXXXXX?feature=oembed" allowfullscreen="" frameborder="0" height="270" width="100%"...iframe

ANy way around it? thank you

**Comment by joselfonseca** [comment]
Please update the field type and check the readme, it has been updated.

Thanks for the issue!
