### ISSUE TITLE
Impossible to delete link

### ISSUE THREAD

**Issue by tiipiik** [WeDreamPro/PyroCMS-Video-URL-FieldType#6]
Hi there, this field type is really awsome, but how do you do when you want to remove the video from a page ? Deleting the link currently not delete db record, so delete = oh, my video is steel here oO !!

**Comment by joselfonseca** [comment]
Hi there! Good observation, let me get my hands on it tonight! Thanks for report!

**Comment by tiipiik** [comment]
Hi :)  Did you have time to fix it ? It is possible that it is the video field (hidden), that did not reset when you delete the url in the video_url field (visible field). Hope it helps.

**Comment by joselfonseca** [comment]
This has been taken care of, thanks for reporting the issue and also many thanks for using our field type.

**Comment by tiipiik** [comment]
Thank you for your reactivity ! :)
